# RLlib PPO distributed config for Guandan
ray:
  address: null  # e.g., 'auto' for cluster, or 'ray://host:10001'
env_config:
  observation_mode: comprehensive
  max_steps: 3000
train:
  num_workers: 8
  rollout_fragment_length: 200
  train_batch_size: 32000
  sgd_minibatch_size: 1024
  num_sgd_iter: 10


